include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_types_as_parameter_names
    - empty_catches
    - no_duplicate_case_values
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_single_quotes
    - prefer_void_to_null
    - unrelated_type_equality_checks

analyzer:
  errors:
    missing_required_param: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
