#!/bin/bash

clear
echo "====================================================="
echo "   FIX FOR 'Command PhaseScriptExecution failed'     "
echo "====================================================="
echo ""
echo "This script will guide you through the steps to fix the Xcode build error."
echo ""
echo "STEP 1: Xcode will open automatically when this script completes."
echo ""
echo "STEP 2: In Xcode, follow these steps to fix the build error:"
echo ""
echo "   a. Click on the 'Runner' project in the left sidebar"
echo "   b. Click on 'Build Phases' tab"
echo "   c. Expand the 'Run Script' phase (there may be more than one)"
echo "   d. Find the script that contains 'xcode_backend.sh'"
echo "   e. Check the box 'Show environment variables in build log'"
echo "   f. For each Run Script phase, select the option 'Using timing'"
echo "      in the dropdown menu above the script text field"
echo ""
echo "STEP 3: Clean the build folder:"
echo "   a. In Xcode's menu, select Product > Clean Build Folder"
echo ""
echo "STEP 4: Try building the app again:"
echo "   a. Make sure your iPhone is selected in the device dropdown"
echo "   b. Click the Play (▶) button to build and run"
echo ""
echo "If the error persists, try these additional steps:"
echo ""
echo "STEP 5: Check for permission issues:"
echo "   a. In Xcode, click on Runner > Signing & Capabilities"
echo "   b. Make sure 'Automatically manage signing' is checked"
echo "   c. Select your Apple ID in the Team dropdown"
echo ""
echo "STEP 6: Update the Bundle Identifier if needed:"
echo "   a. Change it to something unique like 'com.yourname.mathscanner'"
echo ""
echo "Opening Xcode now..."
echo "====================================================="

# Open Xcode
open ios/Runner.xcworkspace
