name: math_scanner
description: A math problem scanner app that recognizes and solves math problems.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+4
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.10.0
  path_provider: ^2.1.1
  path: ^1.8.3
  permission_handler: ^11.0.1
  math_keyboard: ^0.3.3
  flutter_math_fork: ^0.7.1
  math_expressions: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
